### PR TITLE
fix footer printing

### LINKED ISSUE #61: Print version truncated in firefox
In firefox (85.0.1 (64-bit) for Ubuntu) pages with images gets truncated.

Steps to reproduce:
1. In firefox go to https://geekdocs.de/usage/menus/
2. Open print preview dialog (Ctrl+p (or command+p?))
3. At the bottom, notice that the final image is truncated and the footer is hidden behind the image only showing part of the leading B.

I'm not sure what causes this. Rendering the print version directly in firefox works fine, it is only the print that doesn't work. I "solved" this on my site by hiding the footer and adding `body{overflow-x: visible}` in the print css.

This may very well be a firefox bug rather than a geekdoc one.

### PR DESCRIPTION
**Pull request by i7d3v3l0p3r**
Should be fix #61

### CODE REVIEW

**Review by xoxys — COMMENTED** [review]
I guess we can remove https://github.com/thegeeklab/hugo-geekdoc/blob/a27cedcf9f43a8fd69d3ee5498ca452fda282604/src/sass/_print.scss#L33 in this case as it should take no effect on display: block?

**Comment by i7d3v3l0p3r** [comment]
Without it `main` have `display: flex`, and footer rendering incorrectly

**Comment by xoxys** [comment]
No, what I mean is:

```
 main {
    flex-direction: column-reverse;
  }
```

This block can be removed because it is useless now.

**Comment by i7d3v3l0p3r** [comment]
Oh, sorry. Fixed.

**Comment by xoxys** [comment]
Thanks :+1:

**Pull request merged**
