### PR TITLE
feat: add ja language support

### PR DESCRIPTION
**Pull request by usergreen**
I translated the page for Japanese.
Thank you.

### CODE REVIEW

**Comment by xoxys** [comment]
@usergreen Thanks, I've added some missing translations. Can you verify them?

**Comment by usergreen** [comment]
xoxys, thank for your fixes.
I think the followings might be more appropriate:
Line 47: propertylist_required: 必須
Line 49: propertylist_default: 既定値

**Comment by xoxys** [comment]
Thanks!

**Comment by usergreen** [comment]
It seems appears that I made a mistake when I tried to synchronize my repository with the main.

**Comment by xoxys** [comment]
I've created a new one.

**Comment by usergreen** [comment]
Thank you.

**Pull request closed without merging**
